name = "cf-rss"
compatibility_date = "2024-02-24"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间配置 - 使用环境变量引用ID
# 您需要在Cloudflare Dashboard中设置KV_NAMESPACE_ID环境变量
[[kv_namespaces]]
binding = "RSS_KV"
id = "70b5fa36973d4d369374b67f15e96294"

[site]
bucket = "./dist"

[build]
command = "npm run build"
directory = "dist"

[build.upload]
format = "service-worker"

[env.production]
pages_build_output_dir = "dist"

[functions]
directory = "functions"

# 定时任务配置 - 每30分钟更新一次缓存
[triggers]
crons = ["*/30 * * * *"] 